### ISSUE TITLE
I cannot run M1

### ISSUE THREAD

**Issue by BardiyevAbdulla** [markiv/SwiftUI-Shimmer#13]
it runs with Rosseta but it doesn't run without Rosseta.  Xcode version 14.3.1
<img width="723" alt="Screenshot 2023-08-26 at 5 48 41 PM" src="https://github.com/markiv/SwiftUI-Shimmer/assets/110238753/f31ddb16-b876-4320-897f-29ee8daa021d">

**Comment by markiv** [comment]
I'm using it exclusively **without** Rosetta.

Please try some of the following:
(a) Clean your build folder (Xcode: Product > Clean Build Folder)
(b) Reset package caches (Xcode: File > Packages > Reset Package Caches)
(c) Delete derived data `rm -rf ~/Library/Developer/Xcode/DerivedData` and/or
(d) Delete the Swift package cache at `~/Library/org.swift.swiftpm`

I've seen similar problems before when switching between Rosetta and M1.
