### ISSUE TITLE
[Question] Is it possible to add shimmer behind Button text? 

### ISSUE THREAD

**Issue by luma-ai-team** [markiv/SwiftUI-Shimmer#24]
I'm trying to make the shimmer work behind the Button text (I had a shimmer class for UIButton, and it was easier as the title and background are separated). I wonder if it's possible to do it for Button as well. 

Thank you!

**Comment by markiv** [comment]
This is now supported since 1.4.2. You can specify a blend mode:
```swift
Text("Button Text")
	.shimmering(mode: .background)
```
