### ISSUE TITLE
Broken release has higher version number

### ISSUE THREAD

**Issue by RonnyFenrich** [markiv/SwiftUI-Shimmer#27]
The latest release is tagged as 1.4.3
The previous release is 1.5.0 and that's the one that my Xcode pulls automatically as "latest".

Looks like that 1.5.0 one has the broken line
```.mask(LinearGradient(gradient: gradient, startPoint: startPoint, endPoint: endPoint))``` 
which causes a wrong animation (looks strange and different from before).

I think the fixed/last release should be 1.5.1

**Comment by markiv** [comment]
Thanks for reporting that. I've tagged the latest as 1.5.1.
Please let me know of that works for you.

**Comment by RonnyFenrich** [comment]
Just tried it. LGTM
Thanks!
