### ISSUE TITLE
Can we have fix for this issue to make this compilable for Xcode 14, Swift 5.7

### ISSUE THREAD

**Issue by mohit5189** [markiv/SwiftUI-Shimmer#5]
With Xcode 14, I am facing this error, can we please have a updated version for this?

![Screenshot 2022-08-05 at 3 25 46 PM](https://user-images.githubusercontent.com/2517513/183053662-7543f0d9-770e-49b1-a4d5-dcfd75a183bc.png)

**Comment by markiv** [comment]
Just clean your project and derived data and recompile. There are no pre-compiled binaries in the Shimmer library.
